services:

  # ===== ANCHOR DEFINITIONS =====

  # Общие настройки для N8N
  x-service-n8n: &service-n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./data/n8n-files:/home/node/.n8n/binaryData
      - ./data/n8n-workflows:/home/node/.n8n/workflows
    networks:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          memory: 1G

  # ===== END ANCHOR DEFINITIONS =====


  traefik:
    image: traefik:latest # latest для упрощения поддержки
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entryPoints.web.address=:80"
      # For localhost development, use HTTP only (no HTTPS redirect)
      # Comment these lines for production with real domains:
      # - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      # Disable ACME for localhost development
      # Uncomment and configure for production with real domains:
      # - "--certificatesResolvers.myresolver.acme.email=${ACME_EMAIL}"
      # - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./config/traefik:/etc/traefik/dynamic
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      # Use HTTP for localhost development
      - "traefik.http.routers.traefik.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.traefik.entrypoints=websecure"
      # - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD_HASHED}"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  n8n:
    <<: *service-n8n
    profiles: [default, cpu, developer]
    ports:
      - "5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.n8n.entrypoints=websecure"
      # - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s  # Увеличиваем время запуска

  postgres:
    image: pgvector/pgvector:pg17 # Образ с поддержкой pgvector для Graphiti (последняя версия)
    restart: unless-stopped
    profiles: [default, cpu, developer, production]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
      # Передаем переменные для скрипта инициализации (правильные значения)
      - N8N_USER=n8n
      - N8N_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      # - ./scripts/init-pgvector.sql:/docker-entrypoint-initdb.d/01-init-pgvector.sql:ro  # Временно отключен
      - ./scripts/init-n8n-user.sh:/docker-entrypoint-initdb.d/02-init-n8n-user.sh:ro
      # Zep скрипт больше не нужен после перехода на Graphiti
    networks:
      - database
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB} || pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  pgadmin:
    image: dpage/pgadmin4:latest # latest для упрощения поддержки
    restart: unless-stopped
    profiles: [developer]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - frontend
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_DOMAIN}`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.pgadmin.entrypoints=websecure"
      # - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/pgadmin4/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest # latest для упрощения поддержки
    restart: unless-stopped
    profiles: [default, cpu, developer, production]
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`${QDRANT_DOMAIN}`)"
      - "traefik.http.routers.qdrant.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.qdrant.entrypoints=websecure"
      # - "traefik.http.routers.qdrant.tls.certresolver=myresolver"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 5  # Увеличиваем количество попыток
      start_period: 60s  # Увеличиваем время запуска

  # ollama:
  #   <<: *service-ollama
  #   profiles: [default, cpu]
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.ollama.rule=Host(`${OLLAMA_DOMAIN}`)"
  #     - "traefik.http.routers.ollama.entrypoints=websecure"
  #     - "traefik.http.routers.ollama.tls.certresolver=myresolver"
  #     - "traefik.http.services.ollama.loadbalancer.server.port=11434"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 8G
  #       reservations:
  #         cpus: '2'
  #         memory: 4G

  jupyterlab:
    image: jupyter/minimal-notebook:latest # latest для упрощения поддержки
    restart: unless-stopped
    profiles: [developer]
    volumes:
      - jupyter_data:/home/jovyan/work
    networks:
      - frontend
      - backend
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.rule=Host(`${JUPYTER_DOMAIN}`)"
      - "traefik.http.routers.jupyter.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.jupyter.entrypoints=websecure"
      # - "traefik.http.routers.jupyter.tls.certresolver=myresolver"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

include:
  # Graphiti и Neo4j для AI память и граф знаний
  - path: ./compose/graphiti-compose.yaml  # Содержит Graphiti и Neo4j (бывший zep-compose.yaml)
  # - path: ./compose/supabase-compose.yml  # Временно отключен для упрощения диагностики
  - path: ./compose/ollama-compose.yml
  - path: ./compose/optional-services.yml

volumes:
  n8n_storage:
  postgres_storage:
  ollama_data:
  traefik_letsencrypt:
  pgadmin_data:
  qdrant_storage:
  jupyter_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge
  zep-network:
    driver: bridge
