global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'n8n'
    metrics_path: /metrics
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'ollama'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'qdrant'
    metrics_path: /metrics
    static_configs:
      - targets: ['qdrant:6333']