log:
  level: info
  format: json

http:
  host: 0.0.0.0
  port: 8000
  max_request_size: 5242880

postgres:
  user: zep_user
  password: zep_password_123
  host: postgres
  port: 5432
  database: zep
  schema_name: public
  read_timeout: 30
  write_timeout: 30
  max_open_connections: 10

carbon:
  locale: en

graphiti:
  service_url: http://graphiti:8000

# API Secret для аутентификации
api_secret: zep_api_secret_key_here

telemetry:
  disabled: false
  organization_name: n8n-ai-starter-kit
