services:
  # Zep Community Edition был архивирован в апреле 2025
  # Переходим на Graphiti как официальную замену
  
  graphiti:
    image: zepai/graphiti:0.3
    container_name: graphiti
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - ../.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      # Graphiti specific configurations
      - GRAPHITI_HOST=0.0.0.0
      - GRAPHITI_PORT=8000
      - PYTHONPATH=/app
    networks:
      - zep-network
      - backend
    depends_on:
      neo4j:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graphiti.rule=Host(`${GRAPHITI_DOMAIN}`)"
      - "traefik.http.routers.graphiti.entrypoints=web"
      # Disable TLS for localhost development
      # Uncomment for production:
      # - "traefik.http.routers.graphiti.entrypoints=websecure"
      # - "traefik.http.routers.graphiti.tls.certresolver=myresolver"
      - "traefik.http.services.graphiti.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs').read()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  neo4j:
    image: neo4j:5.22.0
    container_name: neo4j-graphiti
    restart: unless-stopped
    ports:
      - "8474:7474"  # HTTP
      - "8687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/zepzepzep
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    networks:
      - zep-network
      - database
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  neo4j_data:

