# Logstash configuration for N8N AI Starter Kit
http.host: "0.0.0.0"
http.port: 9600

# Path settings
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# Queue settings
queue.type: memory
queue.page_capacity: 64mb
queue.max_events: 0
queue.max_bytes: 1gb

# Monitoring
xpack.monitoring.enabled: false
monitoring.enabled: false

# Log level
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# Dead letter queue
dead_letter_queue.enable: false

# Config reload
config.reload.automatic: true
config.reload.interval: 3s

# HTTP API
api.enabled: true
api.environment: "production"
api.http.host: "0.0.0.0"
api.http.port: 9600

# JVM heap
node.name: logstash-node
