# Kibana configuration for N8N AI Starter Kit logging
server.name: "kibana"
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "changeme"

# Security settings (disabled for internal use)
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "fhjskloppd678ehkdfdlliverpoolfcr"
xpack.reporting.encryptionKey: "gedeshtabhashjcuyy66guzggo455fql"
xpack.security.encryptionKey: "frduiplmh655hhbzxnjmnppp4xjmkgf"

# Logging settings
logging.level: info
logging.quiet: false
logging.dest: stdout

# Monitoring
monitoring.enabled: false
xpack.monitoring.enabled: false

# Index patterns
kibana.index: ".kibana"
kibana.defaultAppId: "dashboard"

# Time settings
i18n.locale: "en"
map.includeElasticMapsService: false

# UI settings
server.maxPayloadBytes: 1048576
server.compression.enabled: true

# Advanced settings
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000
elasticsearch.pingTimeout: 3000

# Index management
xpack.index_management.enabled: true

# Dashboard settings
xpack.canvas.enabled: true
xpack.lens.enabled: true

# Search settings
data.search.aggs.shardDelay.enabled: true

# Path settings
path.data: /usr/share/kibana/data

# Performance settings
server.shutdownTimeout: "5s"
ops.interval: 30000

# Dashboard auto-import settings
xpack.spaces.enabled: false
